startinsights/start_insights/doctype/pitch_craft/pitch_craft.js, startinsights/start_insights/doctype/pitch_craft/pitch_craft.json, startinsights/start_insights/doctype/pitch_craft/pitch_craft.py, startinsights/start_insights/doctype/pitch_craft_assign/pitch_craft_assign.json
1. Pitch Craft Doctype Make as Submitable Doctype.
2. Pitch Craft Assign to Make as Submitable Doctype.
3. Pitch Craft Assign to Custom Button Created and Customize works Done.
=> feat:pitch craft assign to customizations

startinsights/website_api/pitch_craft.py
1. Pitch Craft API All Functions added a image url.
=> bug-fix:pitch craft all functions of api added image url

startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
1. Pitch Craft All fields make as Mandatory.
=> feat:pitch craft all fields makes as mandatory

startinsights/website_api/pitch_craft.py
=> bug-fix:pitch craft api documents

startinsights/start_insights/doctype/book_an_expert/book_an_expert.js, startinsights/start_insights/doctype/book_an_expert_table/book_an_expert_table.json, startinsights/website_api/service_list.py
1. Book an Expert Table Added Status Field.
=> feature:book an expert table status added

startinsights/website_api/book_an_expert.py
1. Book an Expert List for Particular Added dict in status.
=> feat:book an expert table status added in dict

startinsights/website_api/book_an_expert.py
1. Book an Expert Table Booked Status removed in filter
=> bug-fix:book an expert table

startinsights/website_api/angel_investing.py
Angel Investing Document video field added in code
=> feature:Angel Investing video changes

startinsights/website_api/investment_deals.py
1. Investment Deals API Company Logo web_url removed and added image_url object.
=> bug-fix:investment deals company logo url added

startinsights/start_insights/doctype/pitch_craft/pitch_craft.json, startinsights/website_api/pitch_craft.py
1. Pitch Craft New API Added for set the saved and Unsaved Services list.
2. API two dict added services list and my services list.
=> feat:pitch craft new added api

startinsights/start_insights/doctype/investment_deals/investment_deals.json, startinsights/start_insights/doctype/investment_team/investment_team.json, startinsights/website_api/investment_deals.py
investment deals child table added and some fields are remove(doc)
=> feature:changes in investment deals

startinsights/website_api/book_an_expert.py
1. Book an Expert List View Total Not Come Now fixed because return statement inside the for loop.
2. Book an Expert particular method child table booking status changed str to bool.
=> bug-fix:book an expert

startinsights/start_insights/doctype/book_an_expert/book_an_expert.json, startinsights/start_insights/doctype/pitch_craft/pitch_craft.json, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.js, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.py, startinsights/start_insights/doctype/pitch_craft_payment/test_pitch_craft_payment.py, startinsights/website_api/pitch_craft.py
1. Pitch Craft Payment Doctype Created for Pitch Craft Service Booking.
=> feat:pitch craft payment

startinsights/website_api/book_an_expert.py
1. Book an Expert added condition in child table status of true or false.
=> feat:book an expert child table status

startinsights/website_api/book_an_expert.py
=> Feat book an expert status

startinsights/start_insights/doctype/book_an_expert/book_an_expert.json, startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json, startinsights/website_api/book_an_expert.py, startinsights/website_api/investor_wise_overview.py, startinsights/website_api/lms_certificate.py, startinsights/website_api/round_wise_overview.py
1. LMS Certificate api creation
=> Feat lms certificate

startinsights/start_insights/doctype/book_an_expert/book_an_expert.json, startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json, startinsights/website_api/book_an_expert.py, startinsights/website_api/investor_wise_overview.py, startinsights/website_api/round_wise_overview.py
=> feature:linkedin field remove

startinsights/hooks.py, startinsights/public/js/service_list.js, startinsights/start_insights/doctype/book_an_expert/book_an_expert.json, startinsights/start_insights/doctype/service_listing/service_listing.json, startinsights/website_api/pitch_craft.py, startinsights/website_api/service_list.py
1. Pitch Craft Payment Method API Date Format Changed.
2. Service Listing Payment Method API Date Format Changed.
3. Book an Expert New Email ID and Attach Field added.
4. Service listing Fields Arranged.
=> feat:api files all date formation

startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.json, startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.md, startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.py
Notification mail for book an expert
=> feature:notification mail for book an expert

startinsights/website_api/startup_deals.py
1. Startup Deals List view api id and name added in json format.
=> bug-fix:startup deals list id added

startinsights/website_api/pitch_craft.py
1. Pitch Craft Path remove and method remove.
=> bug-fix:pitch craft email send format remove

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py
1. Pitch Room Document id name fixed.
2. List view bug fixed.
=> bug-fix:pitch room list and separate id

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py
1. Create Pitch Room API newly added three method of get the attach type and save in file list.
=> feat:create pitch added file list

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py
1. Pitch Room 3 Fields added for Type of Document like PDF and EXCEL. 
2. Removed the doc_type field.
=> feature:pitch room customize

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py
1. Pitch Room Expiry Date Field Added.
=> feat:pitch room date field added

startinsights/website_api/pitch_room.py
1. Pitch room doc type select options changed as pdf,xlsx,docx.
=> bug-fix:pitch room doc type changed

startinsights/start_insights/doctype/pitch_room/pitch_room.json
=> bug-fix:pitch room fields changes

startinsights/website_api/service_list.py
1. Service Listing API Email Alerts path and method removed.
=> bug-fix:service list email path removed

startinsights/website_api/investor_wise_overview.py
1. Investor Graph Wise Dict name Changed.
=> bugfix:investors graph wise

startinsights/start_insights/doctype/investment_deals/investment_deals.json, startinsights/start_insights/doctype/investment_deals_document/investment_deals_document.json, startinsights/start_insights/doctype/investment_deals_document/investment_deals_document.py, startinsights/start_insights/doctype/investment_team/investment_team.json, startinsights/website_api/investment_deals.py
investment deals attachment fields added
=> feature:investment_deals_attachment_fields_added

startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json, startinsights/website_api/investor_wise_overview.py, startinsights/website_api/round_wise_overview.py
1. Investor Wise Graph and list changes.
2. Round Wise Graph and List Changes.
=> feat:investor and round wise api changes

startinsights/website_api/investor_round_wise_graph.py
1. Investor and Round Wise API list and Graph changes fixed.
=> bug-fix:investor and round wise list & Graph

startinsights/website_api/login.py
=> feature:login role added

startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.js, startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json, startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.py, startinsights/start_insights/doctype/pitch_craft_documents_application/test_pitch_craft_documents_application.py, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json, startinsights/start_insights/doctype/profile_application/profile_application.js, startinsights/start_insights/doctype/profile_application/profile_application.json, startinsights/start_insights/doctype/profile_application/profile_application.py, startinsights/start_insights/doctype/profile_application/test_profile_application.py, startinsights/start_insights/doctype/service_listing/service_listing.json, startinsights/website_api/pitch_craft.py, startinsights/website_api/profile.py, startinsights/website_api/service_list.py
1. Pitch Craft Documents Doctype created for Pitch Craft Purchase person uploading the documents will set in that.
2. Profile Creation and Update Doctype.
3. Service Listing new method for payment details.
4. Pitch Craft Payment new Method for Payment details.
=> feat:new changes in api

startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json, startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json
1. Investor and Round wise Read Only Removed.
=> feat:investor and round wise doctype read only removed

startinsights/website_api/service_list.py
1. Service Listing Changes in Payment Method.
=> feat:service listing changes

startinsights/start_insights/doctype/startup_deals/startup_deals.json, startinsights/website_api/startup_deals.py
1. Startup Deals URL Field and Description Fields added.
=> feat:startup deals redeem code changes

startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.js, startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.json, startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.py, startinsights/start_insights/doctype/startup_deal_redeem_user/test_startup_deal_redeem_user.py, startinsights/start_insights/doctype/startup_deals/startup_deals.json, startinsights/website_api/startup_deals.py
1. Startup Deal Redeem User New Doctype Created.
2. Start up Deals API for creating a new redeem user.
3. get deals method new redeem status added.
=> feat:redeem user doctype created

startinsights/start_insights/doctype/captable_management/captable_management.js, startinsights/start_insights/doctype/captable_management/captable_management.json, startinsights/start_insights/doctype/captable_management/captable_management.py, startinsights/start_insights/doctype/captable_management/test_captable_management.py, startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json, startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.py, startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json, startinsights/website_api/investment_deals.py, startinsights/website_api/pitch_craft.py
Captable Management Doctype created
=> feature:captable management doctype created

startinsights/custom.py, startinsights/website_api/pitch_craft.py
1. get url method removed added a custom python file and newly created get domain name for url .
=> feat:get_url method removed added domain name

startinsights/website_api/pitch_craft.py
1. Pitch Craft get domain path bug fixed.
=> bug-fix:pitch craft get domain path fixed

startinsights/website_api/angel_investing.py, startinsights/website_api/book_an_expert.py, startinsights/website_api/investment_deals.py, startinsights/website_api/lms_course.py, startinsights/website_api/login.py, startinsights/website_api/pitch_room.py, startinsights/website_api/pitchdo.py, startinsights/website_api/startup_deals.py
get_domain_name added in all function
=> feature: url change for all function

startinsights/website_api/profile.py
1. Profile API Password Removed.
=> feat:profile api changes

startinsights/website_api/profile.py
1. Profile API output given for same user login details.
=> feat:profile update

startinsights/website_api/profile.py
1. Profile API return args name changed.
=> bug-fix:profile api return name changed

startinsights/website_api/book_an_expert.py, startinsights/website_api/lms_course.py
1. Book an Expert date validation.
2. Lms Course User id passed.
=> Feat book an expert lms

startinsights/website_api/book_an_expert.py
book an expert not equal  current time >= book_time calculation added
=> feature : book an expert current time calculation added

startinsights/start_insights/doctype/captable_management/captable_management.json, startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.js, startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.json, startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.py, startinsights/start_insights/doctype/name_of_the_round/test_name_of_the_round.py, startinsights/start_insights/doctype/profile_application/profile_application.json, startinsights/website_api/captable_management.py, startinsights/website_api/investment_deals.py, startinsights/website_api/login_password.py, startinsights/website_api/pitch_room.py
1. Captable Management API for Creation and list view.
2. Login Password.
3. Pitch Room get user with role.
=> feat:captable management api

startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.js, startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.json, startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.py, startinsights/start_insights/doctype/firm_type_of_investors/test_firm_type_of_investors.py, startinsights/start_insights/doctype/funding_stages/funding_stages.js, startinsights/start_insights/doctype/funding_stages/funding_stages.json, startinsights/start_insights/doctype/funding_stages/funding_stages.py, startinsights/start_insights/doctype/funding_stages/test_funding_stages.py, startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.json, startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.py, startinsights/start_insights/doctype/search_investors/search_investors.js, startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/search_investors/search_investors.py, startinsights/start_insights/doctype/search_investors/test_search_investors.py, startinsights/start_insights/doctype/target_countries/target_countries.json, startinsights/start_insights/doctype/target_countries/target_countries.py, startinsights/start_insights/doctype/user_created_investors/test_user_created_investors.py, startinsights/start_insights/doctype/user_created_investors/user_created_investors.js, startinsights/start_insights/doctype/user_created_investors/user_created_investors.json, startinsights/start_insights/doctype/user_created_investors/user_created_investors.py, startinsights/website_api/pitch_room.py, startinsights/website_api/search_investors.py
1. Search Investors New Doctype and some some linked doctypes.
2. Pitch room Bug-fix.
=> feat:search investors list api

startinsights/website_api/search_investors.py
1. Search Investors Image URL bug fix.
=> bug-fix:search investors image url

startinsights/website_api/search_investors.py
=> bug-fix:image url investors

startinsights/website_api/masters.py
1. Masters API Territory Fixed.
=> bug-fix:masters api fixing

startinsights/website_api/masters.py
=> feat:masters api arranged in single api

startinsights/website_api/masters.py
1. Masters API Db name Changes in key's.
=> feat:masters api key name changed

startinsights/website_api/pitch_craft.py
pitch craft payment details added
=> feature :pitcraft payment details

startinsights/start_insights/doctype/type_of_plan/test_type_of_plan.py, startinsights/start_insights/doctype/type_of_plan/type_of_plan.js, startinsights/start_insights/doctype/type_of_plan/type_of_plan.json, startinsights/start_insights/doctype/type_of_plan/type_of_plan.py, startinsights/website_api/register.py
Customer document create while create user
custom fields added
=> feature: customer document created while create user

startinsights/start_insights/doctype/profile_application/profile_application.py
profile application save customer document created
=> feature:profile application save customer document created

startinsights/start_insights/doctype/dashboard_banner/dashboard_banner.json, startinsights/start_insights/doctype/pitch_craft/pitch_craft.json, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json, startinsights/website_api/banner_api.py, startinsights/website_api/pitch_craft.py
1. Dashboard Banner API Created.
2. Pitch Craft payment status field added.
3. Pitch Craft Doctype Status field removed.
=> feat:corrections and changes in api's

startinsights/start_insights/doctype/book_an_expert/book_an_expert.json, startinsights/start_insights/doctype/captable_management/captable_management.json, startinsights/start_insights/doctype/designation/designation.json, startinsights/start_insights/doctype/document_confirmation/document_confirmation.json, startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.json, startinsights/start_insights/doctype/invested_round/invested_round.json, startinsights/start_insights/doctype/investment_deals/investment_deals.json, startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.json, startinsights/start_insights/doctype/lms_email_settings/lms_email_settings.json, startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.json, startinsights/start_insights/doctype/pitch_craft_assign/pitch_craft_assign.json, startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json, startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json, startinsights/start_insights/doctype/pitch_craft_service_list/pitch_craft_service_list.json, startinsights/start_insights/doctype/pitch_do/pitch_do.json, startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/start_insights/doctype/profile_application/profile_application.json, startinsights/start_insights/doctype/quiz_chapter/quiz_chapter.json, startinsights/start_insights/doctype/quiz_question/quiz_question.json, startinsights/start_insights/doctype/round_type/round_type.json, startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json, startinsights/start_insights/doctype/service_listing/service_listing.json, startinsights/start_insights/doctype/service_module/service_module.json, startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.json, startinsights/start_insights/doctype/startup_deals/startup_deals.json, startinsights/start_insights/doctype/tag_name/tag_name.json, startinsights/start_insights/doctype/target_countries/target_countries.json, startinsights/start_insights/doctype/type_of_plan/type_of_plan.json
Disabled fields added in all parent doctype
=> feature:Disabled fields added in all parent doctype

startinsights/website_api/search_investors.py
1. Search Investors API page count type change as int to str.
=> feat:search investors api page count

startinsights/website_api/search_investors.py
1. Search Investors API Int to Str.
=> bug-fix:search investors api str to int

startinsights/website_api/search_investors.py
1. search investors api str to int.
=> feat:api corrections in search investors

startinsights/website_api/search_investors.py
1. Search Investors Calculate Method max count changes as 10 to 8.
=> feat:serach investors changes in calculate correction

startinsights/website_api/register.py
1. create register account method removed args linkedin, company name,login type.
=> feat:register api changes

startinsights/website_api/register.py
1. Register API given user details.
=> feat:register api given return user details

startinsights/website_api/register.py
1. Account Register as Lead local Variable and Customer Creation bug fix.
=> Bug fix register local variable

startinsights/website_api/register.py
1. Register API Return Status Changed and Bug Fixed.
=> bug-fix:register api return status fixed

startinsights/start_insights/doctype/funding_crm/funding_crm.js, startinsights/start_insights/doctype/funding_crm/funding_crm.json, startinsights/start_insights/doctype/funding_crm/funding_crm.py, startinsights/start_insights/doctype/funding_crm/test_funding_crm.py, startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.js, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py, startinsights/start_insights/doctype/search_investors_favourites/test_search_investors_favourites.py, startinsights/start_insights/doctype/user_created_investors/user_created_investors.json, startinsights/start_insights/doctype/user_created_investors/user_created_investors.py, startinsights/website_api/funding_crm.py, startinsights/website_api/search_investors.py, startinsights/website_api/user_creation_investor.py
1. Funding CRM doctype Created.
2. Fundinig CRM new doc created in add investor after insert.
3. List view the funding crm status wise data.
4. Update the funding crm status user wise.
=> feat:funding crm new created

startinsights/website_api/funding_crm.py, startinsights/website_api/user_creation_investor.py
1. Funding CRM array issue fixes and overall count.
2. User Created Investor list contact no null to empty issue fixed,
=> bug-fix:funding crm array and count added for overall

startinsights/start_insights/doctype/funding_crm/funding_crm.json, startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py, startinsights/website_api/funding_crm.py, startinsights/website_api/search_investors.py, startinsights/website_api/user_creation_investor.py
1. Funding CRM field added.
2. Search Investors Favourites create a new in funding crm.
=> feat:funding crm and search investors

startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
=> bug-fix:search investors favourites class file corrections

startinsights/website_api/search_investors.py
1. Get Search Investors Method dict added favourite status added.
=> feat:get search investors method added status

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/website_api/search_investors.py
1. Search Filter Added for List only four
=> feat:search investors filter corrected and changed

startinsights/website_api/search_investors.py
1. Search Investors Condition if the funding stage list is empty all search investors will show.
=> bug-fix:search investors funding stage empty list added

startinsights/start_insights/doctype/investor_application/investor_application.js, startinsights/start_insights/doctype/investor_application/investor_application.json, startinsights/start_insights/doctype/investor_application/investor_application.py, startinsights/start_insights/doctype/investor_application/test_investor_application.py
1. Investor Application for Getting Verify Code.
=> Feat investor application

startinsights/website_api/search_investors.py
1.Get Search Investors List view favourite status condition changed.
=> bug-fix:search investors favourites get list

startinsights/website_api/funding_crm.py
1. Funding CRM update crm status method Search Investors Type Changed.
=> bug-fix:funding crm update status method changes

startinsights/start_insights/doctype/investor_application/investor_application.js, startinsights/start_insights/doctype/investor_application/investor_application.py
investor application email trigger 
if check box is already enable not send the mail
=> feature: investor application email send

startinsights/start_insights/doctype/profile_application/profile_application.py, startinsights/website_api/register.py
1. Register API Corrections in Creating a lead , type of User is startups means create profile and customer.
2. if the type of User is Investor means create a verify code once accepted the verify code the investor account created the same profile and customer created.
=> feat:register api corrections

startinsights/start_insights/doctype/investor_application/investor_application.json, startinsights/website_api/register.py
1. Register API Investors Account Additional added password and mobile no.
=> feat:register api investor creation

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/start_insights/doctype/pitch_room_documents_upload/pitch_room_documents_upload.json, startinsights/start_insights/doctype/pitch_room_documents_upload/pitch_room_documents_upload.py, startinsights/website_api/pitch_craft.py, startinsights/website_api/pitch_room.py
1. Pitch Room Changes in New Design UI.
=> feat:pitch room doctype changes

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py
document upload for pitch room
=> feature:document upload for pitch_room

startinsights/website_api/pitch_room.py
document upload for child table pitch room correction
=> feature:document upload for child table pitch room correction

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py, startinsights/website_api/search_investors.py
1. Recommended Investors Corrections.
=> bug-fix:recommended search investors

startinsights/start_insights/doctype/profile_application/profile_application.json, startinsights/website_api/forget_api.py
1. Forget API Reset Password API Bug fixed.
=> bug-fix:forget api reset password fix

startinsights/website_api/forget_api.py
=> bug-fix:api auth code

startinsights/start_insights/doctype/my_services/my_services.json, startinsights/start_insights/doctype/services/services.json, startinsights/website_api/pitch_room.py, startinsights/website_api/services.py
1. My Services List View Corrections
2. Pitch Room first dict has empty.
=> feat:my services api corrections

startinsights/website_api/pitch_room.py, startinsights/website_api/services.py
1. Services List View Corrections.
=> bug-fix:my services corrections

startinsights/website_api/services.py
1.Services List View added service status.
=> feat:my services status added

startinsights/website_api/login.py
1. Login API response null values changes as empty.
=> bug-fix:login api null values become empty

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/start_insights/doctype/shared_users/shared_users.json, startinsights/start_insights/doctype/shared_users/shared_users.py, startinsights/website_api/pitch_room.py
pitch room shared user added in child table
=> feature:pitch room shared user added in child table

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/website_api/pitch_room.py, startinsights/website_api/services.py
1. Pitch room List view Corrections.
2. Services Corrections.
=> feat:pitch room api corrections

startinsights/website_api/pitch_room.py
1. Pitch Room Get Details Method Room ID Parameter removed.
=> bug-fix:pitch room get details

startinsights/start_insights/doctype/startup_deals/startup_deals.json, startinsights/website_api/startup_deals.py
1. Deals API Bug Issues Fixed.
=> bug-fix:deals api issues fixed

startinsights/website_api/pitch_room.py
1. Pitch Room List API empty dict method moved to before for loop.
=> feat:pitch room list api method moved

startinsights/website_api/pitch_room.py
1. Pitch Room Old Feature Get Shared Users List only Type of User is Investors.
=> old-feat:pitch room get user role details

startinsights/website_api/pitch_room.py
1. Bug Fix for pitch room type of user changed as customer group
=> bug-fix:old feature corrections

startinsights/start_insights/doctype/shared_users/shared_users.json, startinsights/website_api/pitch_room.py
shared user append in child table notes field added
=> feature:shared user append in child table notes field added

startinsights/website_api/pitch_room.py
1. Pitch While share the room to investors the investor will see all the details.
=> feat:pitch room share room link details

startinsights/website_api/pitch_room.py
1. Pitch Room Shared User less the code size.
=> bug-fix:pitch room shared user corrections

startinsights/website_api/pitch_room.py
pitch room doc upload correction
=> feature:pitch room doc upload correction

startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json, startinsights/website_api/pitch_room.py
1. Documents Upload New Types added.
=> feat:pitch room documents upload changes

startinsights/website_api/pitch_room.py
1. Pitch Room Document Upload Bug fixed.
=> bug-fix:pitch room document upload method

startinsights/website_api/lms_course.py
1. LMS Course Get favourite object name changed.
=> bug-fix:get favourite course object name changed

startinsights/website_api/lms_course.py
Get Favourite Courses key name changed as courses_list.
=> bug-fix:favourite course key name changed as courses list

startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.json, startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.py, startinsights/start_insights/doctype/registered_event/registered_event.js, startinsights/start_insights/doctype/registered_event/registered_event.json, startinsights/start_insights/doctype/registered_event/registered_event.py, startinsights/start_insights/doctype/registered_event/test_registered_event.py, startinsights/start_insights/doctype/si_events/si_events.js, startinsights/start_insights/doctype/si_events/si_events.json, startinsights/start_insights/doctype/si_events/si_events.py, startinsights/start_insights/doctype/si_events/test_si_events.py, startinsights/website_api/event.py
1. Get the Event for Both Live and Recorded Event Details
2. While a User Register a Event it creates a new registered event record.
=> feat:event api for both live and recorded event

startinsights/website_api/event.py
1. Local variable not mentioned bug fixed for recorded event.
=> bug-fix:get event local variable

startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.json, startinsights/start_insights/doctype/si_events/si_events.js, startinsights/start_insights/doctype/si_events/si_events.json, startinsights/website_api/event.py
1. Event Doctype Live event start datetime and end datetime added.
2. Event Description added.
3. Event Child Table Description.
=> feat:event fields and logics changes

startinsights/website_api/event.py
1. Recorded Event ID not added Now Bug Fixed.
=> bug-fix:event id added

startinsights/start_insights/doctype/pitch_room/pitch_room.json, startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.js, startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.json, startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.py, startinsights/start_insights/doctype/pitch_room_notes/test_pitch_room_notes.py, startinsights/website_api/pitch_room.py
1. Pitch  Room Update.
2. Docs Upload and details update.
=> feat:pitch room edit room and update room

startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json, startinsights/website_api/pitch_room.py, startinsights/website_api/profile.py
1. Pitch Update Method Changes and Get Pitch Room List changes.
=> feat:pitch room update changes

startinsights/website_api/pitch_room.py
1. Remove Pitch Room Get Details for Particular Room.
=> remove:pitch room get details particular room

startinsights/website_api/pitch_room.py
1. Pitch Room Document Already Is there if the user want to remove the documents remove method created.
=> feat:pitch room documents removed method

startinsights/custom.py, startinsights/website_api/pitch_room.py
1. Pitch Room Doc Count zero Removed.
=> bug-fix:pitch room doc count zero remove

startinsights/website_api/captable_management.py, startinsights/website_api/profile.py
1. Profile List View
2. Captable Management Bug Fixed.
=> feat:profile list view

startinsights/website_api/captable_management.py
1. Captable Management List View Zero to string changed.
=> bug-fix:captable management zero will be string

startinsights/website_api/captable_management.py
1. Captable Management List view round wise object not created we fixed the bug.
=> bug-fix:captable list view round wise object bug fixed

startinsights/website_api/pitch_room.py
1. Pitch Room Update Document count local variable not mentioned now its mentioned as doc count.
=> bug-fix:pitch room update docupload count local variable issue

startinsights/website_api/profile.py
1. Profile List View None Type Data Applied as Empty String.
=> bug-fix:profile list view none type empty string applied

startinsights/website_api/profile.py
1. Profile list view dict key changes.
=> changes:profile list view dict key changes

startinsights/website_api/profile.py
1. Profile Changes List view key name company changes as company name.
=> bug-fix:profile changes list view key fixed

startinsights/start_insights/doctype/funding_crm/funding_crm.json, startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py, startinsights/start_insights/doctype/user_created_investors/user_created_investors.json, startinsights/website_api/funding_crm.py, startinsights/website_api/login.py, startinsights/website_api/search_investors.py, startinsights/website_api/user_creation_investor.py
1. Funding CRM investor status changed as sortlist to shortlist.
2. Search Investors None Type Empty String added.
3. User Created Investors status changed as sortlist to shortlist.
4. Funding CRM Code Changes.
5. Login API key name company to company name changed.
6. Search Investors py file after insert method status changed as sortlist to shortlist.
7. User Created Investors create investors api changes.
=> feat:add investors changes

startinsights/website_api/search_investors.py
Investors list min and max count is empty we assign zero in type of string.
=> feat:search investors

startinsights/start_insights/doctype/my_services/my_services.json, startinsights/start_insights/doctype/process_steps/process_steps.json, startinsights/start_insights/doctype/services_document_upload_table/services_document_upload_table.json, startinsights/start_insights/doctype/services_document_upload_table/services_document_upload_table.py, startinsights/website_api/services.py
1. My Services Process Steps Child table new field added as Doc Upload Check box for view the document upload button in UI.
2. My Service New Child table User Documents Upload for users uploading the documents process wise.
=> feat:my services user document upload method

startinsights/start_insights/doctype/my_service_deliverables/my_service_deliverables.json, startinsights/start_insights/doctype/my_service_deliverables/my_service_deliverables.py, startinsights/start_insights/doctype/my_services/my_services.json, startinsights/website_api/services.py
1. Service Tracking for My Services.
=> feat:service tracking status

startinsights/website_api/services.py
=> feat:my services details

startinsights/website_api/my_services.py
1. My services Chat Conversation Set Method and Get Method.
=> feat:my services chats conversation

startinsights/website_api/my_services.py, startinsights/website_api/services.py
1. Chat Conversation Method Moved to services file and in get details method another object.
=> feat:my services chat changed to services

startinsights/start_insights/doctype/service_listing/service_listing.json, startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.json, startinsights/website_api/banner_api.py, startinsights/website_api/search_investors.py, startinsights/website_api/service_list.py
1. Service listing Doctype link book an expert changed as fundraising experts.
=> feat:fundraising experts changes in service listing

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/website_api/search_investors.py
=> feat:search bar investors

startinsights/website_api/search_investors.py
1. Search Bar method list name not added now bug fixed.
=> bug-fix-search bar investors

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/sector_focus_table/sector_focus_table.json, startinsights/start_insights/doctype/sector_focus_table/sector_focus_table.py, startinsights/website_api/search_investors.py
1. Search Investors Newly Added Sector Focus Child Table
=> feat:serach investors added search bar in list method

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/website_api/search_investors.py
1. search investors get list min and max size string to int change
=> bug-fix:search investor list view string to int

startinsights/website_api/pitch_room.py, startinsights/website_api/register.py, startinsights/website_api/search_investors.py
1. Pitch Room new Changes.
2. Search Investors get List .
3. Register Changes.
=> feat:bug fixing and new changes api's

startinsights/after_install.py
1. After Install Customer Group Data will Automatically Come.
=> feat:after install customer group data

startinsights/hooks.py, startinsights/start_insights/doctype/tag_name/tag_name.json, startinsights/start_insights/doctype/user_created_investors/user_created_investors.json
=> feat:tag naming series

startinsights/website_api/captable_management.py, startinsights/website_api/funding_crm.py
1. Funding CRM List View Changes.
=> feat:funding crm changes for list view

startinsights/start_insights/doctype/funding_crm/funding_crm.json, startinsights/website_api/funding_crm.py
=> feat:funding crm delete api

startinsights/website_api/funding_crm.py
1. Funding CRM Notes field added.
=> feat:funding crm notes added

startinsights/website_api/funding_crm.py
1. Funding CRM investor name bug fixed.
=> bug-fix:funding crm type of investor

startinsights/website_api/funding_crm.py
1. funding crm list view notes data added.
=> feat:funding crm notes data added

startinsights/website_api/funding_crm.py
1. Funding CRM notes script written.
=> bug-fix:funding crm notes

startinsights/website_api/funding_crm.py
1.User Created Investors Save changes update code.
=> feat:user created investors save changes worked

startinsights/start_insights/doctype/service_payment/service_payment.py, startinsights/website_api/funding_crm.py, startinsights/website_api/my_services.py, startinsights/website_api/services.py
1. My Services Chat Bug fixed.
=> bug-fix:services chat for my services

startinsights/website_api/pitch_room.py, startinsights/website_api/services.py
=> feat:currency format change

startinsights/website_api/funding_crm.py, startinsights/website_api/services.py
1. Funding CRM Currency change
=> feat:funding currency change format

startinsights/website_api/search_investors.py
1. Search Investors Currency Changed.
=> feat:search investors currency change

startinsights/website_api/lms_course.py
1. LMS certificate for showing in lms details api.
=> feat:lms certificate in lms details

startinsights/website_api/services.py
=> feat:my service payment invoice

startinsights/website_api/services.py
1. Invoice service not mentioned.
=> bug-fix:my services invoice

startinsights/start_insights/doctype/fundraising_experts/fundraising_experts.json, startinsights/start_insights/doctype/services/services.json, startinsights/website_api/pitch_room.py, startinsights/website_api/service_list.py, startinsights/website_api/services.py
1.Pitch Room File Limit Upload issue and Shared User After Shared user showing issue.
2.Fundraising Expert Connected Doctypes field_name changed.
3.Service Listing Creation Service New doc Fundraising ID field name changed.
=> bug-fix:api bug fixing

startinsights/start_insights/doctype/fundability_quiz/fundability_quiz.js, startinsights/start_insights/doctype/fundability_quiz/fundability_quiz.json, startinsights/start_insights/doctype/fundability_quiz_flow/fundability_quiz_flow.js, startinsights/start_insights/doctype/fundability_quiz_flow/fundability_quiz_flow.json, startinsights/start_insights/doctype/fundability_quiz_flow/fundability_quiz_flow.py, startinsights/start_insights/doctype/fundability_quiz_flow/test_fundability_quiz_flow.py, startinsights/start_insights/doctype/fundability_quiz_flow_table/fundability_quiz_flow_table.json, startinsights/start_insights/doctype/fundability_quiz_flow_table/fundability_quiz_flow_table.py, startinsights/website_api/fundability_quiz.py
1. Fundability Question and options Doctype.
2. Fundability Quiz Questions Flow Doctype.
3. Fundability API.
=> feat:fundability quiz doctype and api

startinsights/start_insights/doctype/fundability_quiz/fundability_quiz.json, startinsights/website_api/fundability_quiz.py, startinsights/website_api/search_investors.py
1. Fundability quiz type of question.
2. Search Investors Disabled Feature.
=> bug-fix-fundability quiz

startinsights/start_insights/doctype/search_investors/search_investors.json, startinsights/start_insights/doctype/services/services.json
1. Services Disabled Function.
2. Search Investors Draft Status Changed.
=> feat:services and search investors

startinsights/start_insights/doctype/fundability_quiz_user_response/fundability_quiz_user_response.js, startinsights/start_insights/doctype/fundability_quiz_user_response/fundability_quiz_user_response.json, startinsights/start_insights/doctype/fundability_quiz_user_response/fundability_quiz_user_response.py, startinsights/start_insights/doctype/fundability_quiz_user_response/test_fundability_quiz_user_response.py, startinsights/start_insights/doctype/quiz_response/quiz_response.json, startinsights/start_insights/doctype/service_payment/service_payment.py, startinsights/website_api/fundability_quiz.py
=> feat:fundability quiz doctypes

startinsights/custom.py, startinsights/website_api/pitch_room.py
1. Pitch Room ID
2. Domain Custom.
=> feat:pitch room update and domain customize

startinsights/start_insights/doctype/fundability_quiz/fundability_quiz.json, startinsights/start_insights/doctype/fundability_quiz_flow/fundability_quiz_flow.js, startinsights/start_insights/doctype/fundability_quiz_flow/fundability_quiz_flow.py, startinsights/start_insights/doctype/fundability_quiz_user_response/fundability_quiz_user_response.json, startinsights/start_insights/doctype/quiz_response/quiz_response.json, startinsights/website_api/fundability_quiz.py
1. Fundability Customize Code.
=> feat:fundability customise

startinsights/website_api/fundability_quiz.py, startinsights/website_api/search_investors.py, startinsights/website_api/startup_deals.py
1. Fundability Response Changes.
2. Search Investors Customize
3. startup Deals Customize
=> feat:customize api

startinsights/start_insights/doctype/captable_bridge_round_type/captable_bridge_round_type.js, startinsights/start_insights/doctype/captable_bridge_round_type/captable_bridge_round_type.json, startinsights/start_insights/doctype/captable_bridge_round_type/captable_bridge_round_type.py, startinsights/start_insights/doctype/captable_bridge_round_type/test_captable_bridge_round_type.py, startinsights/start_insights/doctype/captable_instrument/captable_instrument.js, startinsights/start_insights/doctype/captable_instrument/captable_instrument.json, startinsights/start_insights/doctype/captable_instrument/captable_instrument.py, startinsights/start_insights/doctype/captable_instrument/test_captable_instrument.py, startinsights/start_insights/doctype/captable_management/captable_management.json, startinsights/start_insights/doctype/captable_round_type/captable_round_type.js, startinsights/start_insights/doctype/captable_round_type/captable_round_type.json, startinsights/start_insights/doctype/captable_round_type/captable_round_type.py, startinsights/start_insights/doctype/captable_round_type/test_captable_round_type.py, startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json, startinsights/website_api/captable_management.py, startinsights/website_api/fundability_quiz.py, startinsights/website_api/masters.py
1. Captable Management API and Masters API.
2. Fundability Bug Fixing.
=> feat:captable management and fundability quiz

startinsights/start_insights/doctype/captable_bridge_round_type/captable_bridge_round_type.json, startinsights/start_insights/doctype/captable_instrument/captable_instrument.json
1. Captable Management Json File Update.
=> feat:captable json file updated

startinsights/start_insights/doctype/captable_management/captable_management.json, startinsights/start_insights/doctype/founders_table/founders_table.json, startinsights/start_insights/doctype/founders_table/founders_table.py, startinsights/website_api/captable_management.py
1. Captable Creation API
2. Captable List View and Graph API.
=> feat:captable management new api

startinsights/start_insights/doctype/captable_bridge_round_type/captable_bridge_round_type.json, startinsights/start_insights/doctype/captable_instrument/captable_instrument.json, startinsights/start_insights/doctype/captable_round_type/captable_round_type.json, startinsights/website_api/captable_management.py, startinsights/website_api/masters.py
1. Captable Management Bug Fixing 
2. Masters API Order Wise.
=> bug-fix:captable management bug fix api

startinsights/start_insights/doctype/captable_instrument/captable_instrument.json, startinsights/start_insights/doctype/captable_round_type/captable_round_type.json
1. Bug fixing in captable masters json fixing.
=> bug-fix:captable masters json fixing

startinsights/website_api/masters.py
1. Masters API for Captable Management.
=> bug-fix:masters api

startinsights/start_insights/doctype/profile_application/profile_application.json, startinsights/start_insights/doctype/si_events/si_events.json, startinsights/website_api/captable_management.py, startinsights/website_api/event.py, startinsights/website_api/fundability_quiz.py, startinsights/website_api/masters.py
1. Profile Application New Masters Fields Created.
2. Events Doctype Register URL field Created.
3. Captable Management API Created.
4. Fundability Quiz API.
5. Masters API Bug Fixing.
=> feat:new api for customizations
